### ISSUE TITLE
AçıkAkademi üzerinde yayınlanan 33 video’luk Sanayi 4.0 İleri Seviye Eğitimleriyle Akıllı Nesneler (IoT) Dünyası eğitim seti yayına alındı.

### ISSUE THREAD

**Issue by saridogan** [polatengin/polatengin.github.io#7]
Merhaba engin bey

Açık akademi üzerinde yayınladığınız videolarınıza malesef artık ulaşamıyoruz.

Bu videolar geçekden eğitimime çok katkıda bulunuyordu. Bu videoları temin edebilirmiyim ?

Yardımlarınızı rica ediyorum. 

Kolay Gelsin

**Comment by polatengin** [comment]
Selamlar,

_Açık Akademi_ ne yazık ki kapandı ve _CloudSociety_ ile birleştirildi.

Şansımıza, **Sanayi 4.0 İleri Seviye Eğitimleriyle Akıllı Nesneler Dünyasına Giriş Yapmak İstiyorum** eğitimini _CloudSociety_ üzerine taşıdılar.

Şu adresten aynı eğitimlere erişmeye devam edebilirsiniz; [Sanayi 4.0 İleri Seviye Eğitimleriyle Akıllı Nesneler Dünyasına Giriş Yapmak İstiyorum](https://cloudsociety.fastlane.live/courses/course-v1:OpenAcademy+Sanayi-1+2018_T3/info)

Eğer _CloudSociety_ hesabınız yoksa önce bir hesap oluşturmanız lazım (_Ücretsiz_ 😄)

**Comment by ozrmustafa** [comment]
Yine erişilemiyor :(
